language: python

# Use container-based infrastructure
sudo: false

# Test environments
matrix:
  include:
    - env: TOXENV=py27-dj17
    - env: TOXENV=py33-dj17
    - env: TOXENV=py34-dj17
    - env: TOXENV=py27-dj18
    - env: TOXENV=py33-dj18
    - env: TOXENV=py34-dj18
    - env: TOXENV=py35-dj18
      python: 3.5
    - env: TOXENV=py27-dj19
    - env: TOXENV=py34-dj19
    - env: TOXENV=py35-dj19
      python: 3.5
    - env: TOXENV=flake8

# Package installation
install:
  - pip install tox coveralls wheel

# Run tests
script:
  - tox

# Call subsequent services
after_success:
  - coveralls

# Automate deployment after success
deploy:
  provider: pypi
  user: texperience
  password:
    secure: "c3v0CaEUkGf+s0yP8Bmd4R8HLYYfHL5M8e7cprrV5V99R8K6Gb4rhwczCJjZDCAFgiMxFqRTkouQqaX+7oDyDupwZoWitZ90Xr1DhuSPJOaxWnhbFY7ZYGx1SgpntY6+38Im8SYCZcawTbk255xrPdgFTRtMtAT/u2RVYg8fxtI="
  on:
    tags: true
    repo: texperience/django-bootstrap-ui
  distributions: sdist bdist_wheel
